server:
    port: 12007

spring:
    profiles:
        active: '@profiles.active@'
    application:
        name: dhc-app
#    mvc:
#        pathmatch:
#            matching-strategy: ant_path_matcher
#    security:
#        user:
#            name: user
#            roles: admin
#            password: 123456
